@baseUrl = http://localhost:3000
@providerToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InByb3ZpZGVyIiwiaWF0IjoxNzQ2OTQ2NTc0LCJleHAiOjE3NDY5NTAxNzR9.8ICXKvSea-lmbzlGjPUyPMzZ_og8x1zna6BrEqwjsd0

###
POST {{baseUrl}}/provider/login
Content-Type: application/json
    
{
"email": "vinay@gmail.com",
"password": "Vinay@123"
}

###
GET {{baseUrl}}/provider/profile
Authorization: Bearer {{providerToken}}


###
GET {{baseUrl}}/provider/services
Authorization: Bearer {{providerToken}}


###
GET {{baseUrl}}/provider/orders
Authorization: Bearer {{providerToken}}

###
GET {{baseUrl}}/provider/stats
Authorization: Bearer {{providerToken}}