@baseUrl = http://localhost:3000
@providerToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InByb3ZpZGVyIiwiaWF0IjoxNzQ2ODA5NTg3LCJleHAiOjE3NDY4MTMxODd9.VHbQ8CuP5zq6YZg42GWfPDwCGigVQxlpsMI4ZdmdsHc

###
POST {{baseUrl}}/provider/login
Content-Type: application/json
    
{
"email": "rohan.mehta@example.com",
"password": "Rohit@123."
}

###
GET {{baseUrl}}/provider/profile
Authorization: Bearer {{providerToken}}


###
GET {{baseUrl}}/services

###
GET {{baseUrl}}/provider/stats
Authorization: Bearer {{providerToken}}