@baseUrl = http://localhost:3000
@providerToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InByb3ZpZGVyIiwiaWF0IjoxNzQ2NzA5OTA5LCJleHAiOjE3NDY3MTM1MDl9.lHmw_tCM4O1KlH3FtPdjoRwyfSOcSoVth1lJWB7v5jA

###
POST {{baseUrl}}/provider/login
Content-Type: application/json
    
{
"email": "rohan.mehta@example.com",
"password": "Rohit@123."
}




###
GET {{baseUrl}}/services

###
GET {{baseUrl}}/provider/stats/1
Authorization: Bearer {{providerToken}}